model:
  model_name: 'AMGGCN'
  node_dim: 2
  node_hidden_dim: 128
  edge_dim: 1
  edge_hidden_dim: 1
  output_dim: 1
  num_layers: 1
  dropout: 0.2

data:
  dataset: 'CiteSeer'
  data_dir: '/home/zli/Grids/learning-spectral-clustering/data/'
  subset: False

train:
  random_seed: 2020
  cuda: True
  device: 3
  epochs: 2000
  patience: 100
  eval_freq: 5
  saving_best: True
  saving_checkpoint: True
  checkpoint_freq: 100

optimize:
  optimizer: 'Adam'
  lr: 0.002
  weight_decay: 0.001
  momentum: 0.90
  milestones: [1400, 1600, 2400]
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: True
  wandb_project: 'DSAA5002'
