model:
  model_name: 'AMGGCN'
  node_dim: 2
  node_hidden_dim: 128
  edge_dim: 1
  edge_hidden_dim: 1
  output_dim: 1
  num_layers: 1
  dropout: 0.2
  sample_size: 1

data:
  dataset: 'PubMed'
  data_dir: '/home/zli/Grids/learning-spectral-clustering/data/'
  subset: False

train:
  random_seed: 2020
  cuda: True
  device: 0
  epochs: 2000
  patience: 50
  eval_freq: 5
  saving_best: True
  saving_checkpoint: True
  checkpoint_freq: 100

optimize:
  optimizer: 'Adam'
  lr: 0.001
  weight_decay: 0.001
  momentum: 0.90
  milestones: [1000, 1400, 1800]
  gamma: 0.5

log:
  verbose: True
  log: True
  log_dir: './logs'
  wandb: False
  wandb_project: ''
